"""Initial schema

Revision ID: 530699e96751
Revises: af0f5fce743f
Create Date: 2025-11-22 17:49:15.791136

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "530699e96751"
down_revision: str | Sequence[str] | None = "af0f5fce743f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
