"""Initial schema

Revision ID: af0f5fce743f
Revises:
Create Date: 2025-11-22 17:46:23.531079

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "af0f5fce743f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
